spring:
  cloud:
    consul:
      host: localhost
      port: 8500
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

eadhub:
  auth:
    jwtSecret: dGhpcy1pcy1hLXZlcnktbG9uZy1zZWNyZXQta2V5LWZvci1qd3QtYXV0aGVudGljYXRpb24taW4tZWFkaHViLXByb2plY3Q=
    jwtExpirationMs: 3600000
