server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eadhub-payment
    username: postgres
    password: postgres
  cloud:
    consul:
      discovery:
        service-name: eadhub-payment
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, refresh

resilience4j:
  circuitbreaker:
    instances:
      circuitBreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80
        eventConsumerBufferSize: 10

eadhub:
  broker:
    exchange:
      userEventExchange: eadhub.userevent
      paymentEvent: eadhub.paymentevent
      paymentCommandExchange: eadhub.paymentcommandexchange
    queue:
      userEventQueue: eadhub.userevent.payment
      paymentCommandQueue: eadhub.paymentcommandqueue
    key:
      paymentCommandKey: eadhub.paymentcommandkey
