services:
  eadhub-db:
    image: postgres:15
    container_name: eadhub-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - eadhub-db-data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  eadhub-db-data:
