spring:
  application:
    name: eadhub-notification
  profiles:
    active: dev
  cloud:
    config:
      username: eadhub
      password: eadhub123
  config:
    import: "optional:configserver:http://localhost:8888"
