server:
  port: 8080

spring:
  application:
    name: eadhub-api-gateway
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: eadhub
      password: eadhub123
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      server:
        webmvc:
# Removido cors daqui para usar apenas no SecurityConfig.java
          default-filters:
            - DeduplicateResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
          routes:
            - id: eadhub-notification
              uri: lb://eadhub-notification
              predicates:
                - Path=/users/*/notifications/**

            - id: eadhub-authuser
              uri: lb://eadhub-authuser
              predicates:
                - Path=/auth/**, /users/**, /instructors/**

            - id: eadhub-course
              uri: lb://eadhub-course
              predicates:
                - Path=/courses/**, /modules/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
