server:
  port: 8080

spring:
  application:
    name: eadhub-api-gateway
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      server:
        webmvc:
          routes:
            - id: eadhub-authuser
              uri: lb://eadhub-authuser
              predicates:
                - Path=/auth/**, /users/**, /instructors/**

            - id: eadhub-course
              uri: lb://eadhub-course
              predicates:
                - Path=/courses/**, /modules/**

            - id: eadhub-notification
              uri: lb://eadhub-notification
              predicates:
                - Path=/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
