server:
  port: 8087

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: eadhub-authuser
  datasource:
    url: jdbc:postgresql://localhost:5432/eadhub-authuser
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always