server:
  port: 8087

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: eadhub-authuser
  datasource:
    url: jdbc:postgresql://localhost:5432/eadhub-authuser
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

eadhub:
  broker:
    exchange:
      userEvent: eadhub.userevent

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      circuitBreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80
        eventConsumerBufferSize: 10