server:
  port: 8082

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: eadhub-course
  datasource:
    url: jdbc:postgresql://localhost:5432/eadhub-course
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  rabbitmq:
    addresses: amqp://guest:guest@localhost:5672

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

