server:
  port: 8082

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: course
  datasource:
    url: jdbc:postgresql://localhost:5432/eadhub-course
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

authuser:
  service:
    url: http://localhost:8087
