server:
  port: 8888

spring:
  application:
    name: eadhub-config-server
  profiles:
    active: native
  security:
    user:
      name: eadhub
      password: eadhub123
  cloud:
    config:
      server:
        native:
          search-locations: file:./config-repo,file:./../config-repo
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: health
